site_name: 2024 数字逻辑设计 实验指导
theme: 
  name: material

markdown_extensions:
  - markdown.extensions.codehilite
  - markdown.extensions.extra
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.fenced_code
  - markdown.extensions.footnotes
  - markdown.extensions.tables
  - markdown.extensions.nl2br
  - markdown.extensions.smarty
  - markdown.extensions.wikilinks
  - markdown.extensions.md_in_html
  # - markdown.extensions.tidy
  - markdown.extensions.meta

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML'

# markdown_extensions:
#   - markdown.extensions.extra
#   - markdown.extensions.mathjax